### ISSUE TITLE
[Fix] 상품 버그 수정

### ISSUE THREAD

**Issue by bongbongbon** [bongbongbon/compass_back#2]
## TODO
- [ ] 컨트롤러 작성
- [ ] 도메인 파일 작성
- [ ] 가게 CRUD 기능
- [ ] 가게 Search 기능
