### ISSUE TITLE
[Feat] 상품 API

### ISSUE THREAD

**Issue by bongbongbon** [bongbongbon/compass_back#4]
## TODO
- [ ] 컨트롤러 작성
- [ ] 도메인 파일 작성
- [ ] 가게 CRUD 기능
- [ ] 가게 Search 기능

**Comment by bongbongbon** [comment]
가즈아
